---
abstract: 'Web interface for DBIx::Class Schema/ResultSource/ResultSet'
author:
  - 'ChinaXing(陈云星) <chen.yack@gmail.com>'
build_requires:
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
  base: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-DBICAdmin
requires:
  Mojo::Base: 0
  Mojolicious: 0.4
  Web::Util::DBIC::Paging: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.0003
